spring.application.name=ms-db

server.servlet.context-path=/ms-db/api/v1
server.port=${MS_DB_PORT:8082}

logging.level.com.soaint.ms_db=${MS_DB_LEVEL_LOG:DEBUG}

# H2 Datasource Configuration
spring.datasource.url=jdbc:h2:mem:soaintdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${MS_DB_USERNAME:admin}
spring.datasource.password=${MS_DB_PASSWORD:1234}

# Enable H2 Web Console UI
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true