spring.application.name=ms-auth

server.servlet.context-path=/ms-auth/api/v1

logging.level.com.soaint.ms_auth=${MS_DB_LEVEL_LOG:DEBUG}

# H2 Datasource Configuration
spring.datasource.url=jdbc:h2:mem:soaintdb_auth
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${MS_DB_USERNAME:root}
spring.datasource.password=${MS_DB_PASSWORD:1234}

# Enable H2 Web Console UI
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

com.soaint.ms_db.userguest=${MS_DB_USERGUEST:guest}
com.soaint.ms_db.pswdguest=${MS_DB_PSWDGUEST:1234}UserAuth
