spring.application.name=ms-main

server.servlet.context-path=/ms-main/api/v1
server.port=${MS_MAIN_PORT:8081}

spring.cloud.openfeign.okhttp.enabled=true
spring.cloud.openfeign.client.config.default.loggerLevel=full
logging.level.com.example.client=debug
logging.level.com.soaint.ms_main=${MS_MAIN_LEVEL_LOG:DEBUG}

